#!/bin/sh

set -e

if ! [ -r /etc/pkgos/pkgos.conf ] ; then
   echo "Could not read /etc/pkgos/pkgos.conf"
   exit 1
else
   . /etc/pkgos/pkgos.conf
fi

HERE=$(pwd)

cleanup_data () {
    rm -rf ${HERE}/etc
    rm -f ${HERE}/rebuild-list-sid ${HERE}/rebuild-list-experimental
    rm -rf bpo-src uploads
}

cleanup_data
